CREATE TABLE EMP_TEST (
    NAME VARCHAR2(50)
);

INSERT INTO EMP_TEST (NAME) VALUES ('  Ali  ');
INSERT INTO EMP_TEST (NAME) VALUES ('  Sara');
INSERT INTO EMP_TEST (NAME) VALUES ('John  ');
INSERT INTO EMP_TEST (NAME) VALUES ('*Ahmed*');

SELECT TRIM(NAME) FROM EMP_TEST;

SELECT LTRIM(NAME) FROM EMP_TEST;

SELECT RTRIM(NAME)FROM EMP_TEST;

SELECT TRIM('*' FROM NAME) AS TRIMMED_NAME FROM EMP_TEST;

