CREATE TABLE Manager(
	id NUMBER,
	name VARCHAR2(255),
	age NUMBER,
	birth_date DATE,
	address VARCHAR2(255)
)

ALTER TABLE MANAGER DROP COLUMN address;

ALTER  TABLE  Manager ADD (city_address VARCHAR(100), street VARCHAR(100));

ALTER  TABLE  Manager RENAME COLUMN name TO full_name;

SELECT * FROM MANAGER READONLY;

CREATE TABLE OWNER AS SELECT id, full_name AS name, birth_date FROM MANAGER WHERE 1=0;

ALTER TABLE MANAGER RENAME TO MASTER ;

DROP TABLE MASTER;
DROP TABLE OWNER ;

